# Generated by Django 2.1.3 on 2018-11-14 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Website',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('time_cached', models.DateTimeField(auto_now=True)),
                ('html_version', models.CharField(choices=[('5', 'HTML5'), ('4', 'HTML 4.01 Strict'), ('Unknown', 'Unknown')], default='Unknown', max_length=7)),
                ('title', models.CharField(max_length=1000)),
                ('h1s', models.PositiveIntegerField()),
                ('h2s', models.PositiveIntegerField()),
                ('h3s', models.PositiveIntegerField()),
                ('h4s', models.PositiveIntegerField()),
                ('h5s', models.PositiveIntegerField()),
                ('h6s', models.PositiveIntegerField()),
                ('links_internal', models.PositiveIntegerField()),
                ('links_external', models.PositiveIntegerField()),
                ('links_inaccessible', models.PositiveIntegerField()),
                ('has_login_form', models.BooleanField()),
            ],
        ),
    ]
