# Generated by Django 2.1.3 on 2018-11-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website',
            name='time_cached',
            field=models.DateTimeField(),
        ),
    ]
