# Generated by Django 2.1.3 on 2018-11-14 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analyze', '0002_auto_20181114_0132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='website',
            old_name='has_login_form',
            new_name='has_login',
        ),
    ]
